apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: deo
  name: deo-frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deo-frontend
  template:
    metadata:
      labels:
        app: deo-frontend
    spec:
      #imagePullSecrets:
      #- name: ghcr-login-secret
      containers:
      - name: deo-frontend
        image: ghcr.io/arminhartl/deo-webapp-ws25-frontend:sha256-6ce11445df7bf682e3d56c3b66ae94ef61056a14c52d442cc67864675432e3e8
        args: ["--urls", "http://*:2000"]
        ports:
        - containerPort: 2000
        env:
        - name: DEO_BACKEND_URL
          value: "http://deo-backend-svc:3000"
